import Footer from "@/components/Footer";
import HeroContent from "@/components/MainPage/HeroContent";
import Navigation from "@/components/Navigation";
import Head from "next/head";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Beauty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/beauty.ico" />
      </Head>
      <main>
        <Navigation />
        <section>
          <HeroContent data={data} />
        </section>
      </main>
      <Footer />
    </>
  );
}

export async function getStaticProps() {
  const response = await fetch("https://gorest.co.in/public/v2/posts?per_page=5");
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
}
